name: learning_app_python

networks:
  learning_app_global_network:
    external: true

services:
  learning_app_python_service:
    image: python:3.14.3-bookworm
    container_name: learning_app_python_container
    tty: true
    stdin_open: true
    command: >
      bash -c "cd / && git clone https://github.com/siva1b3/agents.git && tail -f /dev/null"
    networks:
      - learning_app_global_network
